/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndktest_LibFuns */

#ifndef _Included_com_example_ndktest_LibFuns
#define _Included_com_example_ndktest_LibFuns
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndktest_LibFuns
 * Method:    ImgToGray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_convertbitmap_Convert_Convert
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
